name: CICD
on:
  - push
  - pull_request
jobs: 
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: web-project/Dockerfile
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
        working-directory: web-project
      - name: Lint npm
        run: npm run lint
        working-directory: web-project/
  docker_test:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "web-project-image"
      CONTAINER_NAME: "web-project-container"
      CONTAINER_PORT: "4173"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build image
        run: docker image build --tag="${IMAGE_NAME}" ./web-project/
      - name: run container
        run: docker container run -d -p "${CONTAINER_PORT}":4173 --name "${CONTAINER_NAME}" "${IMAGE_NAME}"
      - name: Wait container startup
        run: sleep 5
      - name: http test request
        run: curl http://127.0.0.1:"${CONTAINER_PORT}"/
      - name: stop container
        run: docker container stop "${CONTAINER_NAME}"
      - name: remove container
        run: docker container rm "${CONTAINER_NAME}"
  deploy:
    if: github.event_name == 'push' && contains('refs/heads/main', github.ref)
    runs-on: ubuntu-22.04
    needs: [lint,docker_test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./web-project
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web-project:${{ github.ref_name }}
  delivery:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-22.04
    needs: [lint,docker_test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./web-project
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web-project:${{ github.ref_name }}
